[package]
name = "kingly-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
kingly-lib = { path = "../lib", features = [ "trace" ] }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
valuable = "0.1.0"
