[package]
name = "kingly-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
kingly-lib = { path = "../lib" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
interactive_process = "0.1"
crossbeam = "0.8"
itertools = "0.13"
